spring:
  application:
    name: config-client-one
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: ${CUSTOMER_PROFILE:dev}
      label: ${CUSTOMER_BRANCH:profile_default}
      
